### PR TITLE
Solved a program to left rotate an array by d positions.

### PR DESCRIPTION
**Pull request by Sohoxic**
I am Soham Sarkar and I've worked on issue no #7 .

### CODE REVIEW

**Comment by ShivangShandilya** [comment]
@Sohoxic Thanks for the contribution but as you can see this repo has programs only in Java so if you could change your C++ code to a Java one we can make this work 😁

**Comment by ShivangShandilya** [comment]
And also one more thing I'll tell you is that is a really good practice in Open Source, always raise PRs from a different branch rather than the main one as it can cause complications

**Comment by Sohoxic** [comment]
@ShivangShandilya  Okayyy, thanks alot for the insights, will try to make the necessary changes.

**Comment by Sohoxic** [comment]
@ShivangShandilya I have changed the code to java as per your instructions. I have very little knowledge in java so I took the help of ai to convert my c++ code to java and tried running it on my system. It runs just fine. Also I'll try to make changes in a new branch from next time before creating a PR. Thanks alot

**Comment by ShivangShandilya** [comment]
Cool Looks good to me. Let's merge it 😁

**Pull request merged**
